estadosconcaptal=["Aguascalientes",
"Mexicali",
"La Paz",
"San Francisco De Campeche",
"Tuxtla Gutiérrez",
"Chihuahua",
"Ciudad De México",
"Saltillo",
"Colima",
"Victoria De Durango",
"Toluca",
"Guanajuato",
"Chilpancingo",
"Pachuca",
"Guadalajara",
"Morelia",
"Cuernavaca",
"Tepic",
"Monterrey",
"Oaxaca De Juárez",
"Puebla De Zaragoza",
"Santiago De Querétaro",
"Chetumal",
"San Luis Potosí",
"Culiacán",
"Hermosillo",
"Villahermosa",
"Ciudad Victoria",
"Tlaxcala De Xicohténcatl",
"Xalapa",
"Mérida",
"Zacatecas"]

estados1=["Aguascalientes",
"Baja California",
"Baja California Sur",
"Campeche",
"Chiapas",
"Chihuahua",
"Ciudad De México",
"Coahuila",
"Colima",
"Durango",
"Estado De México",
"Guanajuato",
"Guerrero",
"Hidalgo",
"Jalisco",
"Michoacán",
"Morelos",
"Nayarit",
"Nuevo León",
"Oaxaca",
"Puebla",
"Querétaro",
"Quintana Roo",
"San Luis Potosí",
"Sinaloa",
"Sonora",
"Tabasco",
"Tamaulipas",
"Tlaxcala",
"Veracruz",
"Yucatán",
"Zacatecas"]